config/routes.rb
Moji::Application.routes.draw do
  root :to => "home#new"

  get "message/:id", to: "home#show", as: :show_message
  post "translate", to: "home#create", as: :translate

end

app/models/translate.rb
class Translate < ActiveRecord::Base
  attr_accessible :message, :source
  validate :message_format

 def to_emoji
 	emoji_message = []
 	message.each_char do |m|
 		codepoint = (self.convert_hash[m])
    emoji_message << [codepoint.to_i(16)].pack("U*")
    end
 	emoji_message.join
 end

def to_english
	english_message = []
	message.each_char do |m|
		hex = m.codepoints.first.to_s(16)
		english_message << self.convert_hash.invert[hex.upcase].to_s
	end
	english_message.join
end

def convert
  if source == 'english'
    to_emoji
  else
  	to_english
  end 

end

def convert_hash
  YAML.load(File.open(Rails.root.join("map.yml")))['map']
end

def message_format
  valid = true
  if source == 'english'
    message.each_char do |c|
      valid = valid && (' '..'z').cover?(c)
    end
  else
    message.each_char do |c|
      valid = valid && !(' '..'z').cover?(c)
    end
  end
  if !valid 
    errors.add(:message, "Has to be all english or all emoji, try again.")
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
  	@translate = Translate.find(params[:id])
  end

  def new
	@translate = Translate.new
	end

	def create
		@translate = Translate.new(params[:translate])
    
		if @translate.save
			redirect_to show_message_path(@translate), notice: "IT WORKED!"
		else
	      flash.now.alert = "Please correct the following: #{@translate.errors.full_messages.join(', ')}"
	      render :new
    end
	end

end

app/controllers/translate_controller.rb
class TranslateController < ApplicationController

	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def emojify(content)
		html_string = '<img alt="' + content + '" height="20" src="' + asset_path("emoji/unicode/#{content}.png") + '" style="vertical-align:middle" width="20" />'
    html_string if content.present?
  end
end

app/helpers/translate_helper.rb
module TranslateHelper
end

app/views/home/_form.html.erb
<div>
	<%= simple_form_for @translate, url: translate_path do |f| %>
	<%= f.input :message, placeholder: "What would you like to say?", as: :text, input_html: {rows: 10}, error: false %></br>
	<div>
	<%= f.button :submit, class: 'btn btn-primary btn-xlarge', value: "Send" %>
  </div>
  <div>
	<%= f.input :source, as: :radio_buttons, collection:['english', 'emoji'] %>
  </div>
	<% end %>
</div>

app/views/home/new.html.erb
<div class='page-header'>
<h1>Emoji Encryptor!</h1>
<p>Enter a message below, select English as your source if you'd like to encrypt a message, select Emoji as your source if you'd like to decrypt a message.</p>
</div>

<div class='message-form'>
<%= render "home/form" %>
</div>
</br>
</br>
</br>
<div class='footer'>

app/views/home/show.html.erb
<div class="output" >

<p>
  <b>Message:</b>
  <%#=  @translate.to_emoji.map{|emoji| emojify(emoji) }.join('').html_safe %>
  <%= @translate.convert %>
</p>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav pull-left">
  <li><%= link_to 'Built by Ryan Holdaway', 'http://www.rholdy.com/about/' %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) : "Moji" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Moji" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-45550304-2', 'code-moji.com');
      ga('send', 'pageview');
    </script>
  </head>
  <body>
    <%# application layout styled for Twitter Bootstrap 3.0 %>
    <header>
      <nav class="navbar navbar-default navbar-fixed-bottom">
        <div class="container">
            <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
         <div class="row">
           <div class="col-md-12">
             <%= render 'layouts/messages' %>
             <%= yield %>
           </div>
         </div>
      </div>
    </main>
  </body>
</html>